// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetExploration.PlanetExploration.Dal.Data;

#nullable disable

namespace PlanetExploration.Migrations
{
    [DbContext(typeof(PlanetExplorationContext))]
    [Migration("20231127212429_NofkRobot")]
    partial class NofkRobot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanetExploration.PlanetExploration.Core.Models.HumanCaptain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HumanCaptains");
                });

            modelBuilder.Entity("PlanetExploration.PlanetExploration.Core.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("This planet has not been visited yet.");

                    b.Property<int?>("HumanCaptainId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HumanCaptainId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("PlanetExploration.PlanetExploration.Core.Models.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("PlanetRobot", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int>("RobotsId")
                        .HasColumnType("int");

                    b.HasKey("PlanetId", "RobotsId");

                    b.HasIndex("RobotsId");

                    b.ToTable("PlanetRobot");
                });

            modelBuilder.Entity("PlanetExploration.PlanetExploration.Core.Models.Planet", b =>
                {
                    b.HasOne("PlanetExploration.PlanetExploration.Core.Models.HumanCaptain", "HumanCaptain")
                        .WithMany()
                        .HasForeignKey("HumanCaptainId");

                    b.Navigation("HumanCaptain");
                });

            modelBuilder.Entity("PlanetRobot", b =>
                {
                    b.HasOne("PlanetExploration.PlanetExploration.Core.Models.Planet", null)
                        .WithMany()
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanetExploration.PlanetExploration.Core.Models.Robot", null)
                        .WithMany()
                        .HasForeignKey("RobotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
